name: Deploy CIPP-API to Azure Function App

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: cippcoregwt7e
        package: '.'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
